version: '3.4'

services:
  rabbit:
    image: rabbitmq:3.11.4-management-alpine
    container_name: rabbit
    hostname: rabbit_srv
    networks: 
      - netrabbitmq
    ports: 
      - 15672:15672
      - 5672:5672
    environment: 
      TZ: America/Maceio
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongodb_srv
    networks:
      - netrabbitmq
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_DATABASE: message
      TZ: America/Maceio
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    
  mongoexpress:
    image: mongo-express:latest
    container_name: mongoexpress
    hostname: mongoexpress_srv
    networks:
      - netrabbitmq
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      TZ: America/Maceio
    depends_on:
      mongo:
        condition: service_healthy

  netrabbitmq.api:
    image: ${DOCKER_REGISTRY-}netrabbitmqapi
    networks: 
      - netrabbitmq
    depends_on: 
      rabbit:
        condition: service_healthy
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: NetRabbitmq.Api/Dockerfile
    environment:
      RabbitMQSettings__Host: rabbit_srv
      MongoSettings__ConnectionString: mongodb://mongodb_srv:27017
      MongoSettings__DatabaseName: message
      TZ: America/Maceio

  netrabbitmq.worker:
    image: ${DOCKER_REGISTRY-}netrabbitmqworker
    networks: 
      - netrabbitmq
    depends_on:
      rabbit:
        condition: service_healthy
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: NetRabbitmq.Worker/Dockerfile
    environment:
      RabbitMQSettings__Host: rabbit_srv
      MongoSettings__ConnectionString: mongodb://mongodb_srv:27017
      MongoSettings__DatabaseName: message
      TZ: America/Maceio

networks:
  netrabbitmq: